apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lamx82tfm-nodejs 
  janus-idp.io/tekton: lamx82tfm-nodejs
  backstage.io/kubernetes-id: lamx82tfm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lamx82tfm-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  